//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.431
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTRtoNote.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Label_0_Min {
            get {
                return ((int)(this["Label_0_Min"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10")]
        public int Label_1_Min {
            get {
                return ((int)(this["Label_1_Min"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-25")]
        public int Label_2_Min {
            get {
                return ((int)(this["Label_2_Min"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-40")]
        public int Label_3_Min {
            get {
                return ((int)(this["Label_3_Min"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-60")]
        public int Label_4_Min {
            get {
                return ((int)(this["Label_4_Min"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public uint Label_6_Hand_Max {
            get {
                return ((uint)(this["Label_6_Hand_Max"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int ReacquisitionSpanDays {
            get {
                return ((int)(this["ReacquisitionSpanDays"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"123456,123456,123456,123456,123456,123456,123456,123456,123456,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,chiyuki,123456,123456,123456,123456,123456,123456,123456,123456,123456,shakin,shakin,shakin,shakin,shakin,shakin,shakin,shakin,shakin")]
        public string Passwords {
            get {
                return ((string)(this["Passwords"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("74")]
        public int AccountNum {
            get {
                return ((int)(this["AccountNum"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"scout1,scout2,scout3,scout4,scout5,scout6,scout7,scout8,scout9,yukitan01,yukitan02,yukitan03,yukitan04,yukitan05,yukitan06,yukitan07,yukitan08,yukitan09,yukitan10,yukitan11,yukitan12,yukitan13,yukitan14,yukitan15,yukitan16,yukitan17,yukitan18,yukitan19,yukitan20,yukitan21,yukitan22,yukitan23,yukitan24,yukitan25,yukitan26,yukitan27,yukitan28,yukitan29,yukitan30,yukitan31,yukitan32,yukitan33,yukitan34,yukitan35,yukitan36,yukitan37,yukitan38,yukitan39,yukitan40,yukitan41,yukitan42,yukitan43,yukitan44,yukitan45,yukitan46,yukitan47,1scout,2scout,3scout,4scout,5scout,6scout,7scout,8scout,9scout,shobon2,shobon3,shobon4,shobon5,shobon6,shobon7,shobon8,shobon9,shobon10")]
        public string Logins {
            get {
                return ((string)(this["Logins"]));
            }
        }
    }
}
